export const copy = {
  zh: {
    status: 'RAIN LINK // ONLINE',
    missionTitle: '前往单细胞实验区',
    missionCopy: '穿过中央终端，收集数据碎片，从坡道进入雨夜实验区。',
    drive: '驾驶',
    boost: '推进',
    brake: '漂移 / 刹车',
    jump: '跃起',
    reset: '复位',
    nodes: '终端项目',
    visit: '连接现场终端',
    openGithub: '查看 GitHub',
    resume: 'A4 简历',
    soundOn: '声音：开',
    soundOff: '声音：关',
    fallback: '当前设备未启用 WebGL 或偏好减少动态效果。你仍可访问全部项目。',
    fragments: '数据碎片',
    speed: '时速',
    terminalHint: '中央终端可浏览全部项目',
  },
  en: {
    status: 'RAIN LINK // ONLINE',
    missionTitle: 'Reach the single-cell lab',
    missionCopy: 'Cross the transit hub, collect data fragments, and take the ramp into the rain lab.',
    drive: 'Drive',
    boost: 'Boost',
    brake: 'Drift / brake',
    jump: 'Jump',
    reset: 'Reset',
    nodes: 'Terminal projects',
    visit: 'Connect field terminal',
    openGithub: 'View on GitHub',
    resume: 'A4 Resume',
    soundOn: 'Sound: on',
    soundOff: 'Sound: off',
    fallback: 'WebGL is unavailable or reduced motion is enabled. Every project remains accessible below.',
    fragments: 'Data fragments',
    speed: 'Speed',
    terminalHint: 'Browse every project at the central terminal',
  },
};

export const districts = [
  {
    id: 'origin',
    code: 'HUB_00 // IDENTITY',
    title: { zh: '中央交通终端', en: 'Central Transit Terminal' },
    subtitle: { zh: '周子悦 · 生物信息与 AI 工程', en: 'Ziyue Zhou · Bioinformatics & AI Engineering' },
    description: {
      zh: '这座终端连接生物学、计算分析、科研可视化与 AI 工程。进入后可切换浏览全部项目，并继续驾驶前往单细胞实验区。',
      en: 'The terminal connects biology, computational analysis, scientific visualization, and practical AI engineering. Browse every project here, then drive onward to the single-cell lab.',
    },
    highlights: {
      zh: ['上海交通大学本科', '中国科学院大学硕士', 'ziyuezhou221022@gmail.com', 'R / Python / Shell / AI 工作流'],
      en: ['BSc, Shanghai Jiao Tong University', 'MSc, University of Chinese Academy of Sciences', 'ziyuezhou221022@gmail.com', 'R / Python / Shell / AI workflows'],
    },
    tags: ['BIOINFORMATICS', 'MULTI-OMICS', 'AI'],
    color: '#f4e65b',
    position: [0, 20],
    radius: 5.5,
    physical: true,
    href: 'https://github.com/ziyuezhou1',
  },
  {
    id: 'scrna',
    code: 'LAB_01 // SINGLE CELL',
    title: { zh: '单细胞转录组分析管线', en: 'Single-cell RNA-seq Pipeline' },
    subtitle: { zh: '从质控到调控网络的全流程', en: 'From quality control to regulatory networks' },
    description: {
      zh: '面向小鼠脑组织 snRNA-seq 的模块化分析管线，覆盖整合、注释、差异组成、SCENIC、亚群分析、伪时序与 pseudobulk。',
      en: 'A modular snRNA-seq workflow for mouse brain tissue, spanning integration, annotation, differential composition, SCENIC, subclustering, trajectory inference, and pseudobulk analysis.',
    },
    highlights: {
      zh: ['多分辨率细胞注释', 'pySCENIC / GRNBoost2 调控网络', 'Slingshot 与 Monocle2 伪时序'],
      en: ['Multi-resolution cell annotation', 'pySCENIC / GRNBoost2 regulatory networks', 'Slingshot and Monocle2 trajectories'],
    },
    tags: ['SEURAT', 'R', 'PYSCENIC', 'SLURM'],
    color: '#46e7e1',
    position: [0, -15],
    radius: 6.5,
    physical: true,
    href: 'https://github.com/ziyuezhou1/scRNAseq-analysis-pipeline',
  },
  {
    id: 'bulk',
    code: 'ARCHIVE_02 // TRANSCRIPTOME',
    title: { zh: 'Bulk RNA-seq 分析管线', en: 'Bulk RNA-seq Pipeline' },
    subtitle: { zh: 'HPC 上的比对、定量与可变剪接', en: 'Alignment, quantification, and splicing on HPC' },
    description: {
      zh: '以 Shell 配置驱动的转录组处理流程，串联原始数据、RSEM 定量、二级分析与 MAJIQ/VOILA 可变剪接检查。',
      en: 'A configuration-driven shell workflow connecting raw reads, RSEM quantification, downstream analysis, and MAJIQ/VOILA splicing inspection.',
    },
    highlights: {
      zh: ['配置化批处理', 'SLURM 队列执行', '可重复的二级分析入口'],
      en: ['Configuration-driven batches', 'SLURM queue execution', 'Repeatable downstream analysis entry point'],
    },
    tags: ['SHELL', 'RSEM', 'MAJIQ', 'HPC'],
    color: '#ff4778',
    physical: false,
    href: 'https://github.com/ziyuezhou1/bulk_RNA_seq_analysis_pipeline',
  },
  {
    id: 'medagent',
    code: 'ARCHIVE_03 // MEDICAL AI',
    title: { zh: 'MedAgent 医疗 AI 框架', en: 'MedAgent Medical AI Framework' },
    subtitle: { zh: '多模态、RAG 与临床 Agent 协作', en: 'Multimodal models, RAG, and clinical agents' },
    description: {
      zh: '研究型医疗智能体框架，组织多模态模型、临床工作流、多专家会诊、PubMed RAG、知识图谱、安全护栏与可解释性模块。',
      en: 'A research-oriented medical-agent framework combining multimodal models, clinical workflows, multi-expert collaboration, PubMed RAG, knowledge graphs, safety guardrails, and explainability.',
    },
    highlights: {
      zh: ['Plan–Act–Reflect 临床流程', 'DICOM / FHIR / HL7 数据标准', '安全护栏与人工复核'],
      en: ['Plan–Act–Reflect clinical workflow', 'DICOM / FHIR / HL7 standards', 'Guardrails and human review'],
    },
    tags: ['PYTHON', 'LANGGRAPH', 'RAG', 'DICOM'],
    color: '#a87aff',
    physical: false,
    href: 'https://github.com/ziyuezhou1/med-agent',
  },
  {
    id: 'llmpet',
    code: 'ARCHIVE_04 // AGENT UX',
    title: { zh: 'LLMPET Agent 桌面宠物', en: 'LLMPET Agent Desktop Pet' },
    subtitle: { zh: '把 Agent 状态变成可见、可操作的体验', en: 'Making agent state visible and actionable' },
    description: {
      zh: '面向 Claude Code 与 Codex 的桌面伴侣，通过状态机、事件适配器、权限交互、用量计量与多语言界面呈现 Agent 工作状态。',
      en: 'A desktop companion for Claude Code and Codex that visualizes agent work through state machines, event adapters, permission interactions, local metering, and multilingual UI.',
    },
    highlights: {
      zh: ['Claude hooks 与 Codex rollout 监听', '权限、状态与会话交互', 'Windows / macOS 工程实践'],
      en: ['Claude hooks and Codex rollout monitoring', 'Permission, state, and session UX', 'Windows and macOS engineering'],
    },
    tags: ['ELECTRON', 'NODE.JS', 'STATE MACHINE', 'I18N'],
    color: '#7dff91',
    physical: false,
    href: 'https://github.com/ziyuezhou1/LLMPET',
  },
];

export const worldBounds = 48;
export const physicalDistricts = districts.filter((district) => district.physical);
