export const copy = {
  zh: {
    status: 'MINI CITY // OPEN',
    missionTitle: '沿城市道路探索，或前往南侧赛车场',
    missionCopy: '项目地标分布在弯曲主路旁；跟随橙色旗帜前往独立赛车场，靠近起跑格按 E。',
    drive: '驾驶',
    boost: '加速',
    brake: '漂移 / 刹车',
    jump: '跳跃',
    reset: '复位',
    visit: '查看项目',
    openGithub: '查看 GitHub',
    resume: 'A4 简历',
    soundOn: '声音：开',
    soundOff: '声音：关',
    fallback: '当前设备未启用 WebGL。你仍可访问全部项目。',
    fragments: '城市印章',
    speed: '时速',
    terminalHint: '沿主路自由探索；南侧橙色旗帜通往赛车场',
    raceStart: '开始单圈计时赛',
    raceCancel: '退出计时赛',
  },
  en: {
    status: 'MINI CITY // OPEN',
    missionTitle: 'Explore the open road or head to the south circuit',
    missionCopy: 'Project landmarks line the curved main road; follow the orange flags to the dedicated circuit and press E on the grid.',
    drive: 'Drive',
    boost: 'Boost',
    brake: 'Drift / brake',
    jump: 'Jump',
    reset: 'Reset',
    visit: 'Open project',
    openGithub: 'View on GitHub',
    resume: 'A4 Resume',
    soundOn: 'Sound: on',
    soundOff: 'Sound: off',
    fallback: 'WebGL is unavailable. Every project remains accessible below.',
    fragments: 'City stamps',
    speed: 'Speed',
    terminalHint: 'Free drive on the main road; orange flags lead to the circuit',
    raceStart: 'Start one-lap time trial',
    raceCancel: 'Leave race',
  },
};

export const districts = [
  {
    id: 'origin',
    code: 'PLAZA 00 // PROFILE',
    title: { zh: '中央城市广场', en: 'Central City Plaza' },
    subtitle: { zh: '周子悦 · 生物信息与 AI 工程', en: 'Ziyue Zhou · Bioinformatics & AI Engineering' },
    description: {
      zh: '作品集的城市入口，连接生物学、计算分析、科研可视化与 AI 工程。这里可以快速浏览全部项目。',
      en: 'The city entrance connects biology, computational analysis, scientific visualization, and practical AI engineering.',
    },
    highlights: {
      zh: ['上海交通大学本科', '中国科学院大学硕士', 'ziyuezhou221022@gmail.com', 'R / Python / Shell / AI 工作流'],
      en: ['BSc, Shanghai Jiao Tong University', 'MSc, University of Chinese Academy of Sciences', 'ziyuezhou221022@gmail.com', 'R / Python / Shell / AI workflows'],
    },
    tags: ['BIOINFORMATICS', 'MULTI-OMICS', 'AI'],
    color: '#e76f51',
    position: [0, 8],
    radius: 7.5,
    physical: true,
    href: 'https://github.com/ziyuezhou1',
  },
  {
    id: 'scrna',
    code: 'CAMPUS 01 // SINGLE CELL',
    title: { zh: '单细胞研究园区', en: 'Single-cell Research Campus' },
    subtitle: { zh: '从质控到调控网络的全流程', en: 'From quality control to regulatory networks' },
    description: {
      zh: '面向小鼠脑组织 snRNA-seq 的模块化分析管线，覆盖整合、注释、差异组成、SCENIC、亚群分析、伪时序与 pseudobulk。',
      en: 'A modular snRNA-seq workflow spanning integration, annotation, differential composition, SCENIC, subclustering, trajectories, and pseudobulk.',
    },
    highlights: {
      zh: ['多分辨率细胞注释', 'pySCENIC / GRNBoost2 调控网络', 'Slingshot 与 Monocle2 伪时序'],
      en: ['Multi-resolution annotation', 'pySCENIC / GRNBoost2 networks', 'Slingshot and Monocle2 trajectories'],
    },
    tags: ['SEURAT', 'R', 'PYSCENIC', 'SLURM'],
    color: '#4d9c78',
    position: [23, -8],
    radius: 7.5,
    physical: true,
    href: 'https://github.com/ziyuezhou1/scRNAseq-analysis-pipeline',
  },
  {
    id: 'bulk',
    code: 'DEPOT 02 // TRANSCRIPTOME',
    title: { zh: '转录组物流中心', en: 'Transcriptome Logistics Depot' },
    subtitle: { zh: 'HPC 上的比对、定量与可变剪接', en: 'Alignment, quantification, and splicing on HPC' },
    description: {
      zh: '以 Shell 配置驱动的转录组流程，串联原始数据、RSEM 定量、二级分析与 MAJIQ/VOILA 可变剪接检查。',
      en: 'A configuration-driven workflow connecting raw reads, RSEM quantification, downstream analysis, and MAJIQ/VOILA.',
    },
    highlights: {
      zh: ['配置化批处理', 'SLURM 队列执行', '可重复的二级分析入口'],
      en: ['Configuration-driven batches', 'SLURM execution', 'Repeatable downstream analysis'],
    },
    tags: ['SHELL', 'RSEM', 'MAJIQ', 'HPC'],
    color: '#e6a43b',
    position: [-23, -8],
    radius: 7.5,
    physical: true,
    href: 'https://github.com/ziyuezhou1/bulk_RNA_seq_analysis_pipeline',
  },
  {
    id: 'medagent',
    code: 'CLINIC 03 // MEDICAL AI',
    title: { zh: '医疗 AI 中心', en: 'Medical AI Center' },
    subtitle: { zh: '多模态、RAG 与临床 Agent 协作', en: 'Multimodal models, RAG, and clinical agents' },
    description: {
      zh: '研究型医疗智能体框架，组织多模态模型、临床工作流、多专家会诊、PubMed RAG、知识图谱与安全护栏。',
      en: 'A research medical-agent framework combining multimodal models, clinical workflows, PubMed RAG, knowledge graphs, and guardrails.',
    },
    highlights: {
      zh: ['Plan–Act–Reflect 临床流程', 'DICOM / FHIR / HL7 标准', '安全护栏与人工复核'],
      en: ['Plan–Act–Reflect workflow', 'DICOM / FHIR / HL7', 'Guardrails and human review'],
    },
    tags: ['PYTHON', 'LANGGRAPH', 'RAG', 'DICOM'],
    color: '#7b70b6',
    position: [23, 19],
    radius: 7.5,
    physical: true,
    href: 'https://github.com/ziyuezhou1/med-agent',
  },
  {
    id: 'llmpet',
    code: 'STUDIO 04 // AGENT UX',
    title: { zh: 'Agent 交互工作室', en: 'Agent Interaction Studio' },
    subtitle: { zh: '把 Agent 状态变成可见、可操作的体验', en: 'Making agent state visible and actionable' },
    description: {
      zh: '面向 Claude Code 与 Codex 的桌面伴侣，通过状态机、事件适配器、权限交互、用量计量与多语言界面呈现 Agent 工作状态。',
      en: 'A desktop companion for Claude Code and Codex that visualizes agent work through state machines, event adapters, permissions, metering, and i18n.',
    },
    highlights: {
      zh: ['Claude hooks 与 Codex rollout 监听', '权限、状态与会话交互', 'Windows / macOS 工程实践'],
      en: ['Claude hooks and Codex rollout monitoring', 'Permission and session UX', 'Windows and macOS engineering'],
    },
    tags: ['ELECTRON', 'NODE.JS', 'STATE MACHINE', 'I18N'],
    color: '#4f8ca7',
    position: [-23, 19],
    radius: 7.5,
    physical: true,
    href: 'https://github.com/ziyuezhou1/LLMPET',
  },
];

export const worldBounds = 56;
export const physicalDistricts = districts.filter((district) => district.physical);
